# build stage
FROM maven:3.8.8-eclipse-temurin-17 as build
WORKDIR /app
COPY app/pom.xml ./
COPY app/src ./src
RUN mvn -f pom.xml clean package -DskipTests


# run stage
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=build /app/target/karthikWebApp.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]